[project]
name = "eink"
version = "0.1.0"
description = "Raspberry 4 eInk dashboard"
readme = "README.md"
requires-python = "~=3.14.5"
dependencies = [
    "pydantic~=2.13.4",
    "returns~=0.29.0",
    "gpiozero~=2.0.1",
    "cairosvg~=2.8.2",
    "pillow~=12.3.0",
    "jinja2~=3.1.6",
    "httpx~=0.28.1",
    "click~=8.4.2",
    "rich~=15.0.0",
    "spidev~=3.8",
]

[dependency-groups]
dev = [
    "pytest-recording",
    "pytest",
    "ruff",
    "ty",
]

[project.optional-dependencies]
rpi = [
    "lgpio~=0.2.2.0",
]

[project.scripts]
cli = "eink.main:app"

[build-system]
requires = ["uv_build<0.12"]
build-backend = "uv_build"

[tool.uv]
exclude-newer = "2 days"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "COM812",   # Trailing comma missing
    "CPY001",   # Missing copyright notice at top of file
    "D203",     # 1 blank line required before class docstring
    "D212",     # Multi-line docstring summary should start at the first line
]

[tool.ruff.lint.per-file-ignores]
"{test}/**" = [
    "FBT003",   # Boolean positional value in function call
    "S101",     # Use of assert detected
    "SLF001",   # Private member accessed
]

[tool.ruff.lint.flake8-type-checking]
runtime-evaluated-base-classes = ["pydantic.BaseModel"]

[tool.ty.environment]
extra-paths = ["stubs"]

[tool.pytest.ini_options]
anyio_mode = "auto"
testpaths = ["test"]
filterwarnings = [
    "error::DeprecationWarning",
    "error::FutureWarning",
    "error::RuntimeWarning",
    "error::UserWarning",
]
