class SpiDev:
    max_speed_hz: int
    mode: int

    def open(self, bus: int, device: int) -> None: ...
    def close(self) -> None: ...
    def writebytes(self, values: list[int]) -> None: ...
    def writebytes2(self, values: list[int]) -> None: ...
    def xfer3(self, values: list[int]) -> None: ...
