name: ci

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - '**'

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v7
      - run: uv sync --frozen
      - run: uv run --no-sync ruff format --check
      - run: uv run --no-sync ruff check
      - run: uv run --no-sync ty check

  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v7
      - run: uv sync --frozen
      - run: uv run --no-sync pytest
